stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - self-hosted
  script:
    - echo "building"

test:
  stage: test
  tags:
    - self-hosted
  script:
    - echo "testing"

deploy:
  stage: deploy
  tags:
    - self-hosted
  script:
    - echo deploying