stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - self-hosted
  script:
    - echo "building"
    - cp env.example .env
    - pip3 install -r requirements.txt

test:
  stage: test
  tags:
    - self-hosted
  script:
    - echo "testing"
    - cp env.example .env
    - python3 manage.py test

deploy:
  stage: deploy
  tags:
    - self-hosted
  script:
    - echo deploying
    - ssh deploy@192.168.1.103 -o StrictHostKeyChecking=no 'bash /var/www/polling/script/deploy.sh'